package constants

var EmojipediaPlatforms []string = []string{
	"apple",
	"google",
	"samsung",
	"microsoft-3D-fluent",
	"microsoft",
	"whatsapp",
	"twitter",
	"facebook",
	"huawei",
	"joypixels",
	"lg",
	"telegram",
	"animated-noto-color-emoji",
	"microsoft-teams",
	"skype",
	"twitter-emoji-stickers",
	"joypixels-animations",
	"serenityos",
	"toss-face",
	"sony",
	"noto-emoji",
	"openmoji",
	"icons8",
	"emojidex",
	"messenger",
	"htc",
	"softbank",
	"docomo",
	"au-kddi",
	"mozilla",
}
